### ISSUE TITLE
 Invalid data found when processing input

### ISSUE THREAD

**Issue by inansen** [streamproc/Record-Entire-Meeting#2]
Using rmc3.js with media stream recording have a problem.

 "dependencies": {
    "mkdirp": "0.5.1",
    "fluent-ffmpeg" : "2.0.1",
    "gulp": "^3.9.1",
    "node-uuid": "^1.4.1",
    "recordrtc": "^5.3.0",
    "socket.io": "^1.0.6",
    "socket.io-stream": "^0.9.0",
    "stream-recorder": "^0.3.3"
  },

writing file do disk 1
writing file do disk 2
writing file do disk 3
writing file do disk 4
onRecordingStopped
concatenating files in room: room-8d8e5925  for user: user-c5c05e4a  at interval: 4
executing ffmpeg command
ffmpeg exited with code 1: C:\Users\Inan\Desktop\Node\Node\Interview/uploads/room-8d8e5925/c5c05e4a-3.webm: Invalid data found when processing input

i have an arror at second webm file with recordinghelper. Interval =3\* 1000. only first webm file working others not.

**Comment by mevlutsahinn** [comment]
Exactly the same issue here. Only the first video is playable. The application runs on Ubuntu 14.04. Any suggestions?

**Comment by mevlutsahinn** [comment]
Ok. I've found the solution. It seems like an issue about the MediaStremRecorder.js version. I've pulled the latests version from https://github.com/streamproc/MediaStreamRecorder and replaced the MediaStremRecorder.js files on browser side. Now its working..
